#define OP_NULL 0
#define OP_ADD 1
#define OP_SUB 2
#define OP_NEG 3
#define OP_MUL 4
#define OP_DIV 5
#define OP_DIV_INT 6
#define OP_MOD 7
#define OP_EXP 8
#define OP_LOG 9
#define OP_ROOT 10
#define OP_SIN 11
#define OP_COS 12
#define OP_TAN 13
#define OP_SEC 14
#define OP_CSC 15
#define OP_COT 16
#define OP_ASIN 17
#define OP_ACOS 18
#define OP_ATAN 19
#define OP_ASEC 20
#define OP_ACSC 21
#define OP_ACOT 22
#define OP_SINH 23
#define OP_COSH 24
#define OP_TANH 25
#define OP_SECH 26
#define OP_CSCH 27
#define OP_COTH 28
#define OP_ASINH 29
#define OP_ACOSH 30
#define OP_ATANH 31
#define OP_ASECH 32
#define OP_ACSCH 33
#define OP_ACOTH 34
#define OP_SQRT 35
#define OP_LN 36
#define OP_LOGT 37
#define OP_CEIL 38
#define OP_FLOOR 39
#define OP_ROUND 40
#define OP_SIGN 41
#define OP_GCD 42
#define OP_LCM 43
#define OP_TERMINATE 49

#define NR_FUNCTIONS 28
#define ARG_SEPARATOR 50
#define LEFT_PARENTH 51
#define RIGHT_PARENTH 52
#define VAR_BEGIN 53

#define ERR_NULL 0
#define ERR_SYNTAX 1
#define ERR_OVERFLOW 2
#define ERR_UNKNOWN_TOKEN 3

#define INPUT_SIZE 1024
#define OUTPUT_SIZE 512
#define VAR_VAL_SIZE 128
#define STACK_SIZE 256

